### ISSUE TITLE
Update jaxb  dependencies

### ISSUE THREAD

**Issue by Siedlerchr** [koppor/jabref#276]
I can be updated/it has been replaced by a successor, but I could not get it to work, resulting in the same bug as javaee/jaxb-v2#1144
https://github.com/javaee/jaxb-v2

They also have a maven repo.

**Comment by vpandey-i** [comment]
@Siedlerchr   is this issue (javaee/jaxb-v2#1144) fixed in 2.4.0 ?  I am still facing following issue while compiling tools -->

 Execution failed for task ':xjcTask'.
> taskdef A class needed by class org.jvnet.jaxb2_commons.xjc.XJC2Task cannot be found: com/sun/codemodel/CodeWriter

Any input on this would highly appreciated.

**Comment by vpandey-i** [comment]
@Siedlerchr Is this issue ( javaee/jaxb-v2#1144) is fixed in 2.4.0 ? I am still facing issue in 2.4.0 while compiling tools - 

Execution failed for task ':xjcTask'.
> taskdef A class needed by class org.jvnet.jaxb2_commons.xjc.XJC2Task cannot be found: com/sun/codemodel/CodeWriter

Any input would be highly appreciated.

**Comment by Siedlerchr** [comment]
Sorry, I can't help. We still use 2.3.2

**Comment by vpandey-i** [comment]
Is it working fine with 2.3.2 ? I am trying with 2.3.0 and getting similar issues with xjc failed. is there any work around ?

**Comment by Siedlerchr** [comment]
We use jaxb and xjc in version 2.3.2 in groovy plugins:
`    xjc group: 'org.glassfish.jaxb', name: 'jaxb-xjc', version: '2.3.2'`

https://github.com/JabRef/jabref/tree/master/buildSrc/src/main/groovy/org/jabref/build/xjc

**Comment by vpandey-i** [comment]
Thanks @Siedlerchr. I am running with .NoClassDefFoundError: com/sun/codemodel/CodeWriter with jaxb 2.3.x version. May I know which JAVA Version you are running with ?

**Comment by Siedlerchr** [comment]
We are using java 13, you may need this addtional dependencies:
```
    implementation group: 'jakarta.activation', name: 'jakarta.activation-api', version: '1.2.1'
    implementation group: 'jakarta.xml.bind', name: 'jakarta.xml.bind-api', version: '2.3.2'
    implementation group: 'org.glassfish.jaxb', name: 'jaxb-runtime', version: '2.3.2'
```

**Comment by vpandey-i** [comment]
Thanks @Siedlerchr
